# Generated by Django 3.2.8 on 2021-10-14 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.BooleanField()),
                ('mark_time', models.DateTimeField(auto_now=True, verbose_name='Дата последного просмотра')),
                ('matching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to=settings.AUTH_USER_MODEL, verbose_name='Оцениваемый')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
