# Generated by Django 3.2.8 on 2021-10-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Совпадение', 'verbose_name_plural': 'Совпадения'},
        ),
        migrations.AlterField(
            model_name='match',
            name='mark_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последней отметки'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user', 'matching'), name='unique matches'),
        ),
    ]
